Introduction to NumPy
Theory
NumPy (Numerical Python) is a powerful open-source Python library used for numerical computing.
It provides support for:

Multidimensional arrays (ndarray)
Mathematical operations on arrays
Linear algebra, Fourier transforms, random number generation
NumPy is faster than regular Python lists because it uses optimized C libraries internally.
It is the foundation for many data science and machine learning libraries such as Pandas, TensorFlow, SciPy, and Scikit-learn.

Applications
Handling large multidimensional arrays and matrices.
Performing mathematical and statistical operations efficiently.
Data preprocessing in Machine Learning.
Basis for scientific computing libraries.
Used in image processing, signal processing, and simulations.
Vectorization (eliminating loops, improving performance).


3. List of Functions and Their Usage
Some important NumPy functions:

Function	                                           Usage
np.array()	                                 Create an array
np.arange(start, stop, step)	               Create array with range of values
np.zeros((m,n))	                             Create array filled with zeros
np.ones((m,n))	                             Create array filled with ones
np.eye(n)	                                   Identity matrix
np.linspace(start, stop, num)	               Create evenly spaced numbers
np.random.rand(m,n)	                         Random numbers between 0 and 1
np.shape	                                   Get dimensions of array
np.reshape()	                               Reshape array
np.sum(), np.mean(), np.std()	               Aggregation functions
np.min(), np.max(), np.argmin(), np.argmax()    Min/Max values & indices
np.dot(), np.matmul()	                          Matrix multiplication
np.transpose()	                                Transpose of matrix
np.sort()	                                      Sorting array

In [ ]:
# Importing NumPy
import numpy as np

# Creating Arrays
arr1 = np.array([1,2,3,4,5,6]) # 1D
arr2 = np.array([[1, 2, 3], [4, 5, 6],[9,10,11],[11,12,13]])

print("1D Array:", arr1)
print("2D Array:\n", arr2)

# Array with specific values
zeros = np.zeros((5,3))  #3R / 4C
ones = np.ones((2,3))
identity = np.eye(6)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Identity Matrix:\n", identity)

# Range and linspace
arange_arr = np.arange(1, 45, 2)
linspace_arr = np.linspace(1, 10, 10)

print("Arange:", arange_arr)
print("Linspace:", linspace_arr)

# Random numbers
rand_arr = np.random.rand(4,5)
print("Random Array:\n", rand_arr)
otp =( (rand_arr*1000000)).astype(int)
print("Random Array:\n", otp)

1D Array: [1 2 3 4 5 6]
2D Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 9 10 11]
 [11 12 13]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Arange: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43]
Linspace: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Random Array:
 [[0.60268326 0.67284637 0.02923853 0.93497363 0.71175176]
 [0.83377956 0.6281067  0.43827904 0.70006435 0.10110363]
 [0.07743897 0.82367414 0.89509089 0.10372679 0.33787152]
 [0.27694498 0.60324827 0.44261316 0.85106999 0.87534176]]
Random Array:
 [[602683 672846  29238 934973 711751]
 [833779 628106 438279 700064 101103]
 [ 77438 823674 895090 103726 337871]
 [276944 603248 442613 851069 875341]]


In [3]:
import numpy as np

# Example 1: Reshape and Transpose
matrix = np.arange(1, 13).reshape(4, 3)
print("Matrix:\n", matrix)
print("Transpose:\n", matrix.T)

# Example 2: Mathematical operations
arr = np.array([10, 20, 30, 40])
print("Original Array:", arr)
print("Array + 5:", arr + 5)
print("Array squared:", arr ** 2)

# Example 3: Aggregate Functions
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

# Example 4: Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Matrix Multiplication:\n", np.dot(A, B))

# Example 5: Sorting
unsorted = np.array([3, 1, 4, 1, 5, 9])
print("Sorted Array:", np.sort(unsorted))

Matrix:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Transpose:
 [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Original Array: [10 20 30 40]
Array + 5: [15 25 35 45]
Array squared: [ 100  400  900 1600]
Sum: 100
Mean: 25.0
Standard Deviation: 11.180339887498949
Matrix Multiplication:
 [[19 22]
 [43 50]]
Sorted Array: [1 1 3 4 5 9]



Write a Python program using NumPy to perform the following:


Marks = 65, 78, 90, 55, 88

**Tasks:**

Create a NumPy array using these marks

Find the average marks

Find the highest marks

Find the lowest marks

In [4]:
import numpy as np

# Create NumPy array
marks = np.array([65, 78, 90, 55, 88])

# Calculate average
average = np.mean(marks)

# Find highest marks
highest = np.max(marks)

# Find lowest marks
lowest = np.min(marks)

# Display results
print("Marks:", marks)
print("Average Marks:", average)
print("Highest Marks:", highest)
print("Lowest Marks:", lowest)

Marks: [65 78 90 55 88]
Average Marks: 75.2
Highest Marks: 90
Lowest Marks: 55


Introduction to Pandas
Theory
Pandas is a powerful open-source Python library for data manipulation and analysis.
It provides two primary data structures:

Series: One-dimensional labeled array (like a column in Excel).
DataFrame: Two-dimensional labeled data structure (like a table in SQL/Excel).
Pandas is built on NumPy and integrates well with Matplotlib, Scikit-learn, and other data science libraries.
It is widely used for cleaning, transforming, and analyzing structured data.

Applications
Reading and writing data from different file formats (CSV, Excel, SQL, JSON, etc.)
Data cleaning: handling missing values, duplicates.
Data transformation: filtering, grouping, merging, reshaping.
Statistical analysis and summary reports.
Time-series analysis.
Integration with data visualization libraries.

3. List of Functions and Their Usage
Some important Pandas functions:

Function	Usage
pd.Series()	Create a Series
pd.DataFrame()	Create a DataFrame
pd.read_csv()	Load CSV file
pd.read_excel()	Load Excel file
df.head(), df.tail()	First/last rows
df.info(), df.describe()	Summary info/statistics
df['col']	Access column
df[['col1','col2']]	Access multiple columns
df.loc[]	Access rows/columns by labels
df.iloc[]	Access rows/columns by index
df.isnull(), df.dropna(), df.fillna()	Handling missing values
df.drop(columns=[])	Drop columns
df.sort_values()	Sorting
df.groupby()	Grouping and aggregation
df.merge(), df.join(), pd.concat()	Combining DataFrames
df.to_csv()	Save DataFrame to CSV

In [5]:
from typing_extensions import dataclass_transform
# Importing Pandas
import pandas as pd

# Creating a Series
data = [10, 20, 30,40, 40]
print(data)
series = pd.Series(data, index=[1001,1002,1003,'disha','bharti'])
print("Series:\n", series)

# Creating a DataFrame
data_dict = {
    'Name': ['Alice', 'Shubham','Bob', 'Charlie', 'David','Kartik','Kartik','Harshali','Yuvraj'],
    'Age': [24,34, 25, 22,4,17,15,20,20],
    'City': ['New York', 'New Delhi','New Jersey', 'London', 'Tokyo','Mumbai','Chicago','Washington','Washington']

}
print(data_dict)
df = pd.DataFrame(data_dict)
print("\nDataFrame:\n", df)

# Reading CSV file (example)
#df = pd.read_csv("data.csv")

# Basic DataFrame info
print("\nHead:\n", df.head())
print("\nInfo:\n")
print(df.info())
print("\nDescribe:\n", df.describe())

[10, 20, 30, 40, 40]
Series:
 1001      10
1002      20
1003      30
disha     40
bharti    40
dtype: int64
{'Name': ['Alice', 'Shubham', 'Bob', 'Charlie', 'David', 'Kartik', 'Kartik', 'Harshali', 'Yuvraj'], 'Age': [24, 34, 25, 22, 4, 17, 15, 20, 20], 'City': ['New York', 'New Delhi', 'New Jersey', 'London', 'Tokyo', 'Mumbai', 'Chicago', 'Washington', 'Washington']}

DataFrame:
        Name  Age        City
0     Alice   24    New York
1   Shubham   34   New Delhi
2       Bob   25  New Jersey
3   Charlie   22      London
4     David    4       Tokyo
5    Kartik   17      Mumbai
6    Kartik   15     Chicago
7  Harshali   20  Washington
8    Yuvraj   20  Washington

Head:
       Name  Age        City
0    Alice   24    New York
1  Shubham   34   New Delhi
2      Bob   25  New Jersey
3  Charlie   22      London
4    David    4       Tokyo

Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ---

In [6]:
# Example 1: Selecting columns and rows
print("Single Column:\n", df['Name'])
print("\nMultiple Columns:\n", df[['Name', 'Age']])
print("\nRow by index (iloc):\n", df.iloc[1])
print("\nRow by label (loc):\n", df.loc[1])

# Example 2: Filtering data
print("\nPeople older than 18:\n", df[df['Age'] > 18])

# Example 3: Adding a new column
df['Salary'] = [50000, 60000, 55000, 70000,45000,90000,100000,10000,20000]
print("\nWith Salary Column:\n", df)

# Example 4: Handling missing data
df2 = pd.DataFrame({
    'A': [1, 2, None, 4],
    'B': [5, None, None, 8]
})
print("\nOriginal with NaN:\n", df2)
print("\nDrop NaN:\n", df2.dropna())
print("\nFill NaN with 0:\n", df2.fillna(2.0))

# Example 5: GroupBy and Aggregation
grouped = df.groupby('City')['Salary'].mean()
print("\nAverage Salary by City:\n", grouped)

# Example 6: Sorting
print("\nSorted by Age:\n", df.sort_values(by='Age'))

# Example 7: Merging DataFrames
df_extra = pd.DataFrame({
    'Name': ['Hritik', 'Shahrukh'],
    'Department': ['HR', 'IT']
})
merged = pd.merge(df, df_extra, on='Name', how='outer')
print("\nMerged DataFrame:\n", merged)

Single Column:
 0       Alice
1     Shubham
2         Bob
3     Charlie
4       David
5      Kartik
6      Kartik
7    Harshali
8      Yuvraj
Name: Name, dtype: object

Multiple Columns:
        Name  Age
0     Alice   24
1   Shubham   34
2       Bob   25
3   Charlie   22
4     David    4
5    Kartik   17
6    Kartik   15
7  Harshali   20
8    Yuvraj   20

Row by index (iloc):
 Name      Shubham
Age            34
City    New Delhi
Name: 1, dtype: object

Row by label (loc):
 Name      Shubham
Age            34
City    New Delhi
Name: 1, dtype: object

People older than 18:
        Name  Age        City
0     Alice   24    New York
1   Shubham   34   New Delhi
2       Bob   25  New Jersey
3   Charlie   22      London
7  Harshali   20  Washington
8    Yuvraj   20  Washington

With Salary Column:
        Name  Age        City  Salary
0     Alice   24    New York   50000
1   Shubham   34   New Delhi   60000
2       Bob   25  New Jersey   55000
3   Charlie   22      London   70000
4     Dav